In [1]:
import pandas as pd
import numpy as np

# ------------------------- STEP 1: LOAD DATA -------------------------

# Load patient demographics
patients = pd.read_csv("/root/MIMICIV/data/mimic-iv-3.1/hosp/patients.csv")

# Load hospital admissions
admissions = pd.read_csv("/root/MIMICIV/data/mimic-iv-3.1/hosp/admissions.csv")

# Load ICU stays
icustays = pd.read_csv("/root/MIMICIV/data/mimic-iv-3.1/icu/icustays.csv")

# Load diagnoses (ICD codes assigned to patients)
diagnoses = pd.read_csv("/root/MIMICIV/data/mimic-iv-3.1/hosp/diagnoses_icd.csv")

# Load prescriptions (medications administered)
prescriptions = pd.read_csv("/root/MIMICIV/data/mimic-iv-3.1/hosp/prescriptions.csv")

# Load medical procedures (ICD codes for treatments)
procedures = pd.read_csv("/root/MIMICIV/data/mimic-iv-3.1/hosp/procedures_icd.csv")

# Load ICD descriptions (for both ICD-9 and ICD-10)
icd_diagnoses = pd.read_csv("/root/MIMICIV/data/mimic-iv-3.1/hosp/d_icd_diagnoses.csv.gz")
icd_procedures = pd.read_csv("/root/MIMICIV/data/mimic-iv-3.1/hosp/d_icd_procedures.csv.gz")

# Convert ICU stay timestamps to datetime format
icustays['intime'] = pd.to_datetime(icustays['intime'], errors='coerce')
icustays['outtime'] = pd.to_datetime(icustays['outtime'], errors='coerce')


# Define mapping for admission types
emergency_types = ['DIRECT EMER.', 'EW EMER.', 'URGENT']
normal_types = ['AMBULATORY OBSERVATION', 'DIRECT OBSERVATION', 'ELECTIVE', 
                'EU OBSERVATION', 'OBSERVATION ADMIT', 'SURGICAL SAME DAY ADMISSION']

# Create a new column 'admission_category' based on the mapping
admissions['admission_category'] = admissions['admission_type'].apply(
    lambda x: 'EMERGENCY' if x in emergency_types else 'NORMAL'
)

# Check if mapping worked correctly
print(admissions['admission_category'].value_counts())

# ------------------------- STEP 2: MAP ICD CODES TO DESCRIPTIONS -------------------------

# Merge diagnoses with ICD descriptions
diagnoses = diagnoses.merge(icd_diagnoses, on=["icd_code", "icd_version"], how="left")
diagnoses['diagnosis_description'] = diagnoses['long_title'].fillna("Unknown diagnosis")

# Merge procedures with ICD descriptions
procedures = procedures.merge(icd_procedures, on=["icd_code", "icd_version"], how="left")
procedures['procedure_description'] = procedures['long_title'].fillna("Unknown procedure")

# Keep only necessary columns
diagnoses = diagnoses[['subject_id', 'hadm_id', 'diagnosis_description', 'icd_code']]
procedures = procedures[['subject_id', 'hadm_id', 'procedure_description', 'icd_code']]

# ------------------------- STEP 3: COMPUTE AGE AT EVENTS & MORTALITY -------------------------

# Keep only relevant patient information
patients = patients[['subject_id', 'gender', 'anchor_age', 'anchor_year', 'dod']]

# Merge patient data into all event tables
admissions = admissions.merge(patients, on='subject_id', how='left')
icustays = icustays.merge(patients, on='subject_id', how='left')
diagnoses = diagnoses.merge(patients, on='subject_id', how='left')
procedures = procedures.merge(patients, on='subject_id', how='left')
prescriptions = prescriptions.merge(patients, on='subject_id', how='left')

# Convert date columns
admissions['admittime'] = pd.to_datetime(admissions['admittime'])
prescriptions['starttime'] = pd.to_datetime(prescriptions['starttime'])
patients['dod'] = pd.to_datetime(patients['dod'], errors='coerce')

# Compute age at event time
admissions['age_at_event'] = admissions['anchor_age'] + (admissions['admittime'].dt.year - admissions['anchor_year'])
prescriptions['age_at_event'] = prescriptions['anchor_age'] + (prescriptions['starttime'].dt.year - prescriptions['anchor_year'])

# Assign age at death for deceased patients
patients['age_at_death'] = patients['anchor_age'] + (patients['dod'].dt.year - patients['anchor_year'])
patients['death_flag'] = patients['dod'].notna().astype(int)

# Merge mortality data into admissions
admissions = admissions.merge(patients[['subject_id', 'death_flag', 'age_at_death']], on='subject_id', how='left')

##### Adding Died During Visit variable 
# Convert discharge time to datetime format
admissions['dischtime'] = pd.to_datetime(admissions['dischtime'], errors='coerce')

# Determine if the patient died during this admission
admissions['died_during_visit'] = (
    (admissions['death_flag'] == 1) & 
    (admissions['dod'] >= admissions['admittime']) & 
    (admissions['dod'] <= admissions['dischtime'])
).astype(int)

##### Creating how many days until the next hospitalization
# Sort admissions by patient ID and admission time
admissions = admissions.sort_values(by=['subject_id', 'admittime'])

# Get the next admission time per patient
admissions['next_admittime'] = admissions.groupby('subject_id')['admittime'].shift(-1)

# Compute the number of days until the next visit
admissions['days_until_next_visit'] = (admissions['next_admittime'] - admissions['dischtime']).dt.days

# Compute the number of minutes until the next visit
admissions['mins_until_next_visit'] = (admissions['next_admittime'] - admissions['dischtime']).dt.total_seconds() / 60

# Fill NaN values with -1 (for last visit of each patient)
admissions['days_until_next_visit'].fillna(-1, inplace=True)

admissions['mins_until_next_visit'].fillna(-1, inplace=True)

##### How many days from the last visit to the death?
# Get the last discharge time per patient
last_discharge = admissions.groupby('subject_id')['dischtime'].max().reset_index()
last_discharge.rename(columns={'dischtime': 'last_dischtime'}, inplace=True)

# Merge last discharge time into patients data
patients = patients.merge(last_discharge, on='subject_id', how='left')

# Calculate days from last visit to death (if patient died after last visit)
patients['days_from_last_visit_to_death'] = (patients['dod'] - patients['last_dischtime']).dt.days

# If patient didn't die, set the value to NaN or -1
patients.loc[patients['death_flag'] == 0, 'days_from_last_visit_to_death'] = np.nan

admissions = admissions.merge(
    patients[['subject_id', 'days_from_last_visit_to_death']], 
    on='subject_id', 
    how='left'
)

# ------------------------- STEP 4: BUILD TABULAR DATASET -------------------------

# Select main features
features = admissions[['subject_id',
                       'hadm_id',
                       'admittime',
                       'dischtime',
                       'age_at_event',
                       'gender',
                       'admission_type',
                       'admission_category',
                       'discharge_location',
                       'death_flag',
                       'age_at_death',
                       'died_during_visit',
                       'days_from_last_visit_to_death',
                       'days_until_next_visit',
                       'mins_until_next_visit'
                       ]]

# ICU stays: Number of ICU admissions and length of stay per hospitalization
icu_summary = icustays.groupby('hadm_id').agg(
    icu_admissions=('stay_id', 'count'),
    icu_days=('intime', lambda x: (x.max() - x.min()).days)
).reset_index()

# Diagnoses: Count number of diagnoses per hospitalization
diagnosis_summary = diagnoses.groupby('hadm_id').agg(
    num_diagnoses=('icd_code', 'count'),
    diagnosis_list=('diagnosis_description', lambda x: list(x.unique()))
).reset_index()

# Procedures: Count number of procedures per hospitalization
procedure_summary = procedures.groupby('hadm_id').agg(
    num_procedures=('icd_code', 'count'),
    procedure_list=('procedure_description', lambda x: list(x.unique()))
).reset_index()

# Medications: Count number of prescribed drugs per hospitalization
med_summary = prescriptions.groupby('hadm_id').agg(
    num_medications=('drug', 'count'),
    medication_list=('drug', lambda x: list(x.unique()))
).reset_index()

# Merge all features into a single dataset
dataset = features.merge(icu_summary, on='hadm_id', how='left')
dataset = dataset.merge(diagnosis_summary, on='hadm_id', how='left')
dataset = dataset.merge(procedure_summary, on='hadm_id', how='left')
dataset = dataset.merge(med_summary, on='hadm_id', how='left')

# Fill missing values with 0
dataset.fillna({'icu_admissions': 0, 'icu_days': 0, 'num_diagnoses': 0, 'num_procedures': 0, 'num_medications': 0}, inplace=True)
dataset.fillna({'diagnosis_list': 'None', 'procedure_list': 'None', 'medication_list': 'None'}, inplace=True)

/tmp/ipykernel_4045/746790821.py:19: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  prescriptions = pd.read_csv("/root/MIMICIV/data/mimic-iv-3.1/hosp/prescriptions.csv")

admission_category
NORMAL       291667
EMERGENCY    254361
Name: count, dtype: int64

In [2]:
admissions['subject_id'].nunique()

223452

In [3]:
dataset[dataset['subject_id']==11530780][['subject_id','admittime', 'dischtime', 'days_until_next_visit']]

,subject_id,admittime,dischtime,days_until_next_visit
82093,11530780,2150-04-15 03:25:00,2150-04-16 16:20:00,-1.0
82094,11530780,2150-04-15 22:48:00,2150-04-16 00:20:00,80.0
82095,11530780,2150-07-05 23:06:00,2150-07-08 16:20:00,-1.0

In [4]:
admissions_sorted = dataset.sort_values(['subject_id', 'admittime'])

In [5]:
# Check for overlaps (current visit starts before previous ends)
admissions_sorted['overlaps'] = (
    admissions_sorted.groupby('subject_id')['admittime'].shift(-1) < admissions_sorted['dischtime']
)

In [6]:
admissions_sorted[admissions_sorted['overlaps']==True]

,subject_id,hadm_id,admittime,dischtime,age_at_event,gender,admission_type,admission_category,discharge_location,death_flag,...,mins_until_next_visit,icu_admissions,icu_days,num_diagnoses,diagnosis_list,num_procedures,procedure_list,num_medications,medication_list,overlaps
3928,10076639,23684554,2135-12-22 22:53:00,2135-12-23 19:19:00,60,F,EU OBSERVATION,NORMAL,NaN,0,...,-120.0,0.0,0.0,1.0,"[Schizoaffective disorder, unspecified]",3.0,"[Electrocardiogram, Computerized axial tomogra...",0.0,None,True
25110,10482555,24141586,2146-10-02 00:11:00,2146-10-12 11:00:00,21,F,OBSERVATION ADMIT,NORMAL,HOME,0,...,-13844.0,0.0,0.0,3.0,"[Major depressive disorder, recurrent severe w...",0.0,None,29.0,"[Diazepam, HydrOXYzine, LORazepam, Sertraline,...",True
36926,10693757,23954106,2163-04-20 00:00:00,2163-04-22 15:45:00,37,F,URGENT,EMERGENCY,HOME,0,...,-2879.0,0.0,0.0,2.0,[Other mental disorders complicating the puerp...,0.0,None,10.0,"[LORazepam, Senna, Ibuprofen, Polyethylene Gly...",True
53749,11011076,27826883,2178-12-02 21:43:00,2178-12-03 09:15:00,82,M,DIRECT OBSERVATION,NORMAL,NaN,1,...,-120.0,0.0,0.0,6.0,[Other complications due to genitourinary devi...,0.0,None,0.0,None,True
71745,11339384,27383384,2187-09-16 04:36:00,2187-09-26 14:47:00,78,F,EW EMER.,EMERGENCY,SKILLED NURSING FACILITY,0,...,-317.0,1.0,0.0,39.0,"[Other amyloidosis, Acute on chronic diastolic...",0.0,None,106.0,"[Doxycycline Hyclate, Pantoprazole, Metoprolol...",True
75244,11402448,20437968,2138-09-17 17:54:00,2138-09-17 23:12:00,68,F,EU OBSERVATION,NORMAL,NaN,1,...,-59.0,0.0,0.0,11.0,"[Unspecified psychosis, Unspecified episodic m...",0.0,None,0.0,None,True
77609,11443713,22227792,2146-05-16 00:01:00,2146-05-17 23:44:00,87,F,EU OBSERVATION,NORMAL,NaN,1,...,-1413.0,0.0,0.0,10.0,"[Gouty arthropathy, unspecified, Atrial fibril...",0.0,None,0.0,None,True
82093,11530780,26728216,2150-04-15 03:25:00,2150-04-16 16:20:00,22,F,DIRECT OBSERVATION,NORMAL,NaN,0,...,-1052.0,0.0,0.0,4.0,[Other current conditions classifiable elsewhe...,0.0,None,4.0,"[Albuterol Inhaler, Prenatal Vitamins, Acetami...",True
83415,11553072,20836013,2163-03-22 00:07:00,2163-03-23 07:11:00,53,M,EU OBSERVATION,NORMAL,NaN,1,...,-1457.0,0.0,0.0,4.0,"[Alcohol abuse, unspecified, Unspecified essen...",0.0,None,0.0,None,True
85056,11582633,20212371,2133-05-29 22:57:00,2133-05-30 09:43:00,50,F,EU OBSERVATION,NORMAL,NaN,0,...,-8.0,0.0,0.0,1.0,"[Depressive disorder, not elsewhere classified]",0.0,None,0.0,None,True
101799,11890885,22107522,2174-03-04 00:58:00,2174-03-05 10:15:00,31,F,URGENT,EMERGENCY,HOME,0,...,-577.0,0.0,0.0,4.0,"[Other threatened labor, antepartum condition ...",1.0,[Other fetal monitoring],0.0,None,True
105391,11960687,27222233,2133-05-30 16:00:00,2133-05-30 21:27:00,30,F,DIRECT OBSERVATION,NORMAL,NaN,0,...,-4.0,0.0,0.0,1.0,"[Abnormal glucose tolerance of mother, antepar...",2.0,"[Medical induction of labor, Other fetal monit...",0.0,None,True
111154,12064183,23688796,2144-04-09 19:00:00,2144-04-29 15:07:00,70,F,EW EMER.,EMERGENCY,REHAB,0,...,-906.0,2.0,5.0,21.0,"[Subendocardial infarction, initial episode of...",14.0,"[Left heart cardiac catheterization, (Aorto)co...",291.0,"[Aspirin EC, Pneumococcal Vac Polyvalent, Albu...",True
112437,12088183,20048656,2156-10-23 07:56:00,2156-10-23 14:18:00,22,M,EU OBSERVATION,NORMAL,NaN,0,...,-62.0,0.0,0.0,2.0,[Poisoning by other and unspecified anticonvul...,0.0,None,0.0,None,True
117487,12177088,24782976,2149-05-23 01:01:00,2149-05-24 06:29:00,52,M,EU OBSERVATION,NORMAL,NaN,1,...,-757.0,0.0,0.0,2.0,"[Other chest pain, Acute alcoholic intoxicatio...",0.0,None,0.0,None,True
133829,12476296,24523858,2129-10-19 00:11:00,2129-10-23 13:30:00,31,F,URGENT,EMERGENCY,HOME,0,...,-5632.0,0.0,0.0,5.0,"[Oligohydramnios, delivered, with or without m...",1.0,[Episiotomy],14.0,"[Milk of Magnesia, Simethicone, Oxycodone-Acet...",True
141520,12612423,21669279,2188-06-11 22:29:00,2188-06-16 17:58:00,60,M,OBSERVATION ADMIT,NORMAL,PSYCH FACILITY,0,...,-2.0,0.0,0.0,10.0,"[Urinary tract infection, site not specified, ...",0.0,None,27.0,"[Amoxicillin, Clonazepam, Propranolol, Nadolol...",True
195316,13593286,26407350,2161-08-31 18:38:00,2161-09-07 14:01:00,19,M,DIRECT EMER.,EMERGENCY,REHAB,0,...,-831.0,0.0,0.0,7.0,"[Other postoperative infection, Acute osteomye...",5.0,"[Other arthrotomy, ankle, Open biopsy of soft ...",36.0,"[Miconazole Powder 2%, Heparin Flush (10 units...",True
202432,13723491,29784931,2143-03-22 01:25:00,2143-03-24 15:45:00,70,M,EW EMER.,EMERGENCY,PSYCH FACILITY,0,...,-106.0,0.0,0.0,7.0,"[Unspecified psychosis, Diabetes mellitus with...",0.0,None,14.0,"[Sodium Chloride 0.9% Flush, Cyanocobalamin, ...",True
229986,14233347,24907049,2129-10-31 17:43:00,2129-11-02 14:45:00,48,M,EW EMER.,EMERGENCY,PSYCH FACILITY,0,...,-38.0,0.0,0.0,18.0,"[Diabetes with ketoacidosis, type II or unspec...",0.0,None,30.0,"[Insulin, Sodium Chloride 0.9% Flush, Nicotin...",True
234926,14319319,22282287,2156-12-15 13:58:00,2157-02-11 18:53:00,26,M,EW EMER.,EMERGENCY,HOME,0,...,-42813.0,0.0,0.0,7.0,"[Abdominal pain, epigastric, Ulcerative coliti...",0.0,None,17.0,"[Zolpidem Tartrate, Sodium Chloride 0.9% Flus...",True
238935,14388411,28172744,2184-12-18 00:37:00,2184-12-21 14:11:00,59,M,EW EMER.,EMERGENCY,DIED,1,...,-194.0,1.0,0.0,19.0,"[Intracerebral hemorrhage, Acute respiratory f...",1.0,[Continuous invasive mechanical ventilation fo...,40.0,"[0.9% Sodium Chloride, MethylPREDNISolone Sodi...",True
241666,14438637,20942192,2114-04-24 00:00:00,2114-04-27 15:30:00,51,F,SURGICAL SAME DAY ADMISSION,NORMAL,HOME,0,...,-930.0,0.0,0.0,12.0,[Morbid (severe) obesity due to excess calorie...,1.0,"[Excision of Stomach, Percutaneous Endoscopic ...",19.0,"[OxycoDONE Liquid, Acetaminophen IV, Omeprazol...",True
262105,14813830,27175674,2125-12-19 00:00:00,2125-12-20 06:58:00,63,M,EU OBSERVATION,NORMAL,NaN,0,...,-1637.0,0.0,0.0,2.0,"[Difficulty in walking, Alcohol abuse, unspeci...",2.0,"[Computerized axial tomography of head, Other ...",0.0,None,True
289781,15325143,20676359,2193-04-20 22:25:00,2193-04-21 08:40:00,54,M,EU OBSERVATION,NORMAL,NaN,0,...,-10.0,0.0,0.0,5.0,"[Alcohol abuse with intoxication, unspecified,...",0.0,None,0.0,None,True
297858,15464144,26215672,2193-10-12 00:13:00,2193-10-13 02:47:00,59,M,EU OBSERVATION,NORMAL,NaN,0,...,-1376.0,0.0,0.0,3.0,"[Difficulty in walking, Altered mental status,...",0.0,None,0.0,None,True
301346,15524760,29877622,2125-12-25 18:33:00,2125-12-26 08:07:00,54,M,EU OBSERVATION,NORMAL,NaN,0,...,-468.0,0.0,0.0,3.0,"[Difficulty in walking, Alcohol withdrawal del...",0.0,None,0.0,None,True
303762,15567851,20792550,2131-10-02 12:51:00,2131-10-02 14:42:00,42,F,EU OBSERVATION,NORMAL,NaN,0,...,-59.0,0.0,0.0,10.0,"[Major depressive affective disorder, single e...",0.0,None,0.0,None,True
304675,15583423,29263432,2139-01-30 14:00:00,2139-02-01 13:53:00,57,M,EU OBSERVATION,NORMAL,NaN,0,...,-833.0,0.0,0.0,2.0,"[Alcohol abuse, unspecified, Suicidal ideation]",0.0,None,0.0,None,True
324876,15957311,28458168,2160-10-26 04:33:00,2160-10-27 23:00:00,52,M,EW EMER.,EMERGENCY,AGAINST ADVICE,1,...,-1280.0,0.0,0.0,10.0,"[Other postoperative infection, Human immunode...",0.0,None,34.0,"[traZODONE, Docusate Sodium, Sodium Chloride 0...",True
326741,15989769,27138177,2141-12-18 23:12:00,2141-12-21 17:00:00,33,F,EU OBSERVATION,NORMAL,NaN,0,...,-1004.0,0.0,0.0,8.0,"[Other specified cardiac dysrhythmias, Migrain...",0.0,None,26.0,"[Ibuprofen, Lorazepam, Symbicort, ClonazePAM, ...",True
362487,16645602,25252757,2142-09-07 18:23:00,2142-09-14 16:00:00,63,F,EW EMER.,EMERGENCY,SKILLED NURSING FACILITY,1,...,-939.0,0.0,0.0,5.0,"[Other alteration of consciousness, Epilepsy, ...",0.0,None,28.0,"[Clonazepam, OLANZapine (Disintegrating Tablet...",True
368437,16755361,25460698,2138-07-02 08:30:00,2138-07-05 16:00:00,59,M,SURGICAL SAME DAY ADMISSION,NORMAL,SKILLED NURSING FACILITY,0,...,-954.0,0.0,0.0,7.0,"[Cervical spondylosis with myelopathy, Interve...",4.0,"[Other cervical fusion of the anterior column,...",27.0,"[Gabapentin, Insulin, Influenza Virus Vaccine,...",True
380937,16979257,28549465,2112-05-09 00:42:00,2112-05-10 02:00:00,18,F,OBSERVATION ADMIT,NORMAL,HOME,0,...,-40.0,0.0,0.0,6.0,"[Primary inadequate contractions, Diseases of ...",0.0,None,0.0,None,True
382508,17006375,27470235,2173-07-16 20:47:00,2173-07-19 17:25:00,73,M,EW EMER.,EMERGENCY,ACUTE HOSPITAL,0,...,-4.0,0.0,0.0,10.0,"[Major depressive affective disorder, recurren...",0.0,None,18.0,"[Amlodipine, Isosorbide Mononitrate (Extended ...",True
398738,17301514,29850768,2173-09-22 21:10:00,2173-09-22 23:35:00,20,F,EU OBSERVATION,NORMAL,NaN,0,...,-58.0,0.0,0.0,2.0,"[Depressive disorder, not elsewhere classified...",0.0,None,0.0,None,True
421261,17719829,24659429,2153-03-29 14:58:00,2153-03-30 13:57:00,45,M,EU OBSERVATION,NORMAL,NaN,0,...,-21.0,0.0,0.0,5.0,"[Bipolar I disorder, most recent episode (or c...",0.0,None,0.0,None,True
431358,17903094,24913091,2179-04-29 00:22:00,2179-04-30 04:48:00,51,M,EU OBSERVATION,NORMAL,NaN,0,...,-1624.0,0.0,0.0,1.0,"[Alcohol abuse with intoxication, unspecified]",0.0,None,0.0,None,True
444616,18137283,24415972,2127-03-31 16:00:00,2127-04-01 14:54:00,63,F,DIRECT OBSERVATION,NORMAL,NaN,0,...,-880.0,0.0,0.0,7.0,"[Obstruction of bile duct, Primary sclerosing ...",0.0,None,13.0,"[Acetaminophen, Ondansetron, Sertraline, Sodiu...",True
447692,18197813,23893744,2159-05-01 17:02:00,2159-05-09 17:55:00,61,M,EW EMER.,EMERGENCY,SKILLED NURSING FACILITY,1,...,-1064.0,1.0,0.0,19.0,[Anaphylactic reaction due to adverse effect o...,5.0,"[Respiratory Ventilation, Less than 24 Consecu...",61.0,"[Acetylcysteine 20%, QUEtiapine Fumarate, Acet...",True
464158,18507371,27559602,2181-04-25 00:03:00,2181-04-28 12:10:00,32,F,URGENT,EMERGENCY,HOME,0,...,-4366.0,0.0,0.0,5.0,"[Transient hypertension of pregnancy, delivere...",4.0,[Repair of current obstetric laceration of rec...,12.0,"[Docusate Sodium, Ibuprofen, Milk of Magnesia,...",True
481882,18818535,22565406,2168-08-07 14:25:00,2168-08-08 17:20:00,39,F,EU OBSERVATION,NORMAL,NaN,0,...,-1026.0,0.0,0.0,14.0,[Type 2 diabetes mellitus with diabetic autono...,0.0,None,18.0,"[Glucose Gel, Albuterol, Pantoprazole, Clonidi...",True
482190,18824395,22979870,2131-11-15 03:44:00,2131-11-16 15:31:00,42,F,OBSERVATION ADMIT,NORMAL,PSYCH FACILITY,0,...,-2147.0,0.0,0.0,9.0,"[Poisoning by other antidepressants, Major dep...",0.0,None,9.0,"[Diazepam, Acetaminophen, D5 1/2NS, Sodium Chl...",True
500572,19157548,25013375,2125-01-22 00:16:00,2125-01-23 06:50:00,51,M,EU OBSERVATION,NORMAL,NaN,1,...,-1694.0,0.0,0.0,2.0,"[Altered mental status, Alcohol abuse, unspeci...",0.0,None,0.0,None,True
506357,19270999,23711108,2140-02-27 13:19:00,2140-02-29 23:30:00,34,M,EW EMER.,EMERGENCY,PSYCH FACILITY,0,...,-59.0,1.0,0.0,11.0,"[Poisoning-antidepressant, Human immunodeficie...",3.0,"[Spinal tap, Continuous invasive mechanical ve...",11.0,"[Sodium Bicarbonate, 0.9% Sodium Chloride, Nic...",True
520085,19526150,25040473,2190-05-01 07:03:00,2190-05-01 23:36:00,52,F,EU OBSERVATION,NORMAL,NaN,0,...,-659.0,0.0,0.0,2.0,[Unspecified inflammatory disease of female pe...,0.0,None,0.0,None,True
530783,19716964,29450499,2149-01-26 19:50:00,2149-03-03 18:30:00,19,F,DIRECT OBSERVATION,NORMAL,PSYCH FACILITY,0,...,-44622.0,0.0,0.0,6.0,"[Generalized anxiety disorder, Suicidal ideati...",0.0,None,8.0,"[HydrOXYzine, Docusate Sodium, Ramelteon, Hepa...",True
532735,19759225,22567464,2144-08-08 22:14:00,2144-08-12 12:52:00,38,M,EW EMER.,EMERGENCY,HOME,1,...,-757.0,0.0,0.0,13.0,"[Alcohol withdrawal, Gastroesophageal lacerati...",0.0,None,36.0,"[Ondansetron, HYDROmorphone (Dilaudid), Potass...",True

In [7]:
TEST_df = admissions_sorted[admissions_sorted['subject_id']==10076639]

In [8]:
TEST_df

,subject_id,hadm_id,admittime,dischtime,age_at_event,gender,admission_type,admission_category,discharge_location,death_flag,...,mins_until_next_visit,icu_admissions,icu_days,num_diagnoses,diagnosis_list,num_procedures,procedure_list,num_medications,medication_list,overlaps
3928,10076639,23684554,2135-12-22 22:53:00,2135-12-23 19:19:00,60,F,EU OBSERVATION,NORMAL,NaN,0,...,-120.0,0.0,0.0,1.0,"[Schizoaffective disorder, unspecified]",3.0,"[Electrocardiogram, Computerized axial tomogra...",0.0,None,True
3929,10076639,23036582,2135-12-23 17:19:00,2136-01-01 15:30:00,60,F,EW EMER.,EMERGENCY,HOME HEALTH CARE,0,...,-1.0,0.0,0.0,5.0,"[Schizoaffective disorder, chronic with acute ...",0.0,None,32.0,"[Desonide 0.05% Cream, Risperidone (Disintegra...",False

In [9]:
TEST_df = TEST_df.sort_values(by=['subject_id', 'admittime'])
TEST_df = TEST_df.reset_index(drop=True)

In [10]:
TEST_df

,subject_id,hadm_id,admittime,dischtime,age_at_event,gender,admission_type,admission_category,discharge_location,death_flag,...,mins_until_next_visit,icu_admissions,icu_days,num_diagnoses,diagnosis_list,num_procedures,procedure_list,num_medications,medication_list,overlaps
0,10076639,23684554,2135-12-22 22:53:00,2135-12-23 19:19:00,60,F,EU OBSERVATION,NORMAL,NaN,0,...,-120.0,0.0,0.0,1.0,"[Schizoaffective disorder, unspecified]",3.0,"[Electrocardiogram, Computerized axial tomogra...",0.0,None,True
1,10076639,23036582,2135-12-23 17:19:00,2136-01-01 15:30:00,60,F,EW EMER.,EMERGENCY,HOME HEALTH CARE,0,...,-1.0,0.0,0.0,5.0,"[Schizoaffective disorder, chronic with acute ...",0.0,None,32.0,"[Desonide 0.05% Cream, Risperidone (Disintegra...",False

In [11]:
admissions_sorted['subject_id'].nunique()

223452

What can be done in this situation? We can try different approaches, starting from the concatenation in an unique visit of the overlapping visits for all 48 patients. Or, since there are just 48 patients with overlapping over 223452 (i.e., 0.02%) we decide to remove those patients from our dataset.

In [12]:
dataframe_no_overlap = admissions_sorted.groupby('subject_id').filter(lambda x: all(x['overlaps']==False))

In [13]:
dataframe_no_overlap['subject_id'].nunique() # no more overlaps

223404

In [14]:
dataframe_no_overlap[dataframe_no_overlap['mins_until_next_visit']==0]

,subject_id,hadm_id,admittime,dischtime,age_at_event,gender,admission_type,admission_category,discharge_location,death_flag,...,mins_until_next_visit,icu_admissions,icu_days,num_diagnoses,diagnosis_list,num_procedures,procedure_list,num_medications,medication_list,overlaps
185,10002930,28477649,2197-04-07 06:56:00,2197-04-08 19:37:00,52,F,EU OBSERVATION,NORMAL,NaN,1,...,0.0,0.0,0.0,7.0,"[Unspecified psychosis, Suicidal ideation, Uns...",0.0,None,0.0,None,False
970,10017035,29784303,2143-04-10 23:55:00,2143-04-13 11:38:00,25,M,EU OBSERVATION,NORMAL,NaN,0,...,0.0,0.0,0.0,4.0,[Poisoning by other opiates and related narcot...,0.0,None,0.0,None,False
1595,10029211,29967424,2133-08-10 19:42:00,2133-08-13 10:35:00,25,F,EU OBSERVATION,NORMAL,NaN,0,...,0.0,0.0,0.0,6.0,"[Unspecified mood [affective] disorder, Suicid...",0.0,None,0.0,None,False
1621,10029874,23069127,2180-11-13 18:27:00,2180-11-18 19:44:00,67,M,EW EMER.,EMERGENCY,PSYCH FACILITY,0,...,0.0,1.0,0.0,12.0,"[Acute alcoholic intoxication in alcoholism, u...",0.0,None,37.0,"[Sodium Chloride 0.9% Flush, FoLIC Acid, 0.9%...",False
2055,10038688,29585848,2175-06-10 04:43:00,2175-06-12 21:33:00,46,M,OBSERVATION ADMIT,NORMAL,PSYCH FACILITY,1,...,0.0,0.0,0.0,10.0,"[Alcohol withdrawal, Acidosis, Viral hepatitis...",1.0,[Alcohol detoxification],16.0,"[Sodium Chloride 0.9% Flush, Diazepam, Senna,...",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545029,19983279,22656324,2127-12-01 01:15:00,2127-12-04 15:02:00,36,F,EU OBSERVATION,NORMAL,NaN,0,...,0.0,0.0,0.0,4.0,"[Manic episode, unspecified, Post-traumatic st...",0.0,None,0.0,None,False
545053,19983966,29065074,2137-07-11 22:21:00,2137-07-13 13:15:00,85,F,EU OBSERVATION,NORMAL,NaN,0,...,0.0,0.0,0.0,13.0,"[Major depressive disorder, single episode, un...",0.0,None,0.0,None,False
545132,19985349,21686305,2127-09-19 02:04:00,2127-09-19 03:54:00,72,M,EU OBSERVATION,NORMAL,NaN,0,...,0.0,0.0,0.0,3.0,"[Other and unspecified alcohol dependence, uns...",0.0,None,0.0,None,False
545623,19993214,24464076,2170-10-09 15:20:00,2170-10-09 20:10:00,40,M,EU OBSERVATION,NORMAL,NaN,0,...,0.0,0.0,0.0,5.0,"[Unspecified schizophrenia, unspecified, Unspe...",0.0,None,0.0,None,False
545628,19993214,21763179,2172-11-05 14:57:00,2172-11-05 17:44:00,42,M,EU OBSERVATION,NORMAL,NaN,0,...,0.0,0.0,0.0,1.0,"[Unspecified schizophrenia, unspecified]",0.0,None,0.0,None,False

In [15]:
dataframe_no_overlap[dataframe_no_overlap['subject_id']==10002930][['subject_id', 'admittime', 'dischtime', 'days_until_next_visit', 'mins_until_next_visit']]

,subject_id,admittime,dischtime,days_until_next_visit,mins_until_next_visit
182,10002930,2193-08-05 06:18:00,2193-08-05 11:44:00,0.0,1.0
183,10002930,2193-08-05 11:45:00,2193-08-11 09:25:00,977.0,1407060.0
184,10002930,2196-04-14 12:25:00,2196-04-17 15:28:00,354.0,510688.0
185,10002930,2197-04-07 06:56:00,2197-04-08 19:37:00,0.0,0.0
186,10002930,2197-04-08 19:37:00,2197-04-15 12:01:00,1.0,2280.0
187,10002930,2197-04-17 02:01:00,2197-04-17 09:48:00,365.0,526190.0
188,10002930,2198-04-17 19:38:00,2198-04-22 16:02:00,0.0,15.0
189,10002930,2198-04-22 16:17:00,2198-05-04 13:20:00,289.0,416665.0
190,10002930,2199-02-17 21:45:00,2199-02-19 13:38:00,470.0,677765.0
191,10002930,2200-06-05 05:43:00,2200-06-05 10:26:00,252.0,363272.0
192,10002930,2201-02-12 16:58:00,2201-02-13 11:11:00,38.0,55204.0
193,10002930,2201-03-23 19:15:00,2201-03-26 14:24:00,-1.0,-1.0

In [ ]:
# Let us load the landmark_df_evo dataset
landmark_df_evo = pd.read_csv("/root/MIMICIV/src/landmark_df_evo.csv")

In [2]:
import pandas as pd

In [3]:
landmark_df_evo_correct = pd.read_csv("/root/MIMICIV/src/landmark_df_evo_correct.csv")

In [ ]:
landmark_df_evo['subject_id'].nunique()

In [4]:
landmark_df_evo_correct['subject_id'].nunique()

223452

In [20]:
#landmark_df_evo.head()

In [20]:
dataframe_no_overlap_2_merge = dataframe_no_overlap[['subject_id', 'hadm_id', 'admittime', 'dischtime', 'days_until_next_visit', 'mins_until_next_visit']].copy()
dataframe_no_overlap_2_merge.head()

,subject_id,hadm_id,admittime,dischtime,days_until_next_visit,mins_until_next_visit
0,10000032,22595853,2180-05-06 22:23:00,2180-05-07 17:15:00,50.0,72072.0
1,10000032,22841357,2180-06-26 18:27:00,2180-06-27 18:49:00,25.0,37066.0
2,10000032,29079034,2180-07-23 12:35:00,2180-07-25 17:55:00,11.0,16189.0
3,10000032,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,-1.0,-1.0
4,10000068,25022803,2160-03-03 23:16:00,2160-03-04 06:26:00,-1.0,-1.0

In [21]:
dataframe_no_overlap_2_merge['subject_id'].nunique()

223404

In [23]:
# Ensure your DataFrame is sorted by patient and landmark_visit
dataframe_no_overlap_2_merge = dataframe_no_overlap_2_merge.sort_values(['subject_id', 'admittime']).reset_index(drop=True)

# Function to perform transformation
def transform_to_past_variable(group):
    group = group.sort_values('admittime').copy()
    # Shift the values down (future to past)
    group['days_since_last_visit'] = group['days_until_next_visit'].shift(1)
    # First landmark always has -1
    group['days_since_last_visit'].iloc[0] = -1
    # same reasoning for minutes
    group['mins_since_last_visit'] = group['mins_until_next_visit'].shift(1)
    # First landmark always has -1
    group['mins_since_last_visit'].iloc[0] = -1

    return group

# Apply the transformation per patient
dataframe_no_overlap_2_merge = dataframe_no_overlap_2_merge.groupby('subject_id').apply(transform_to_past_variable).reset_index(drop=True)

In [24]:
dataframe_no_overlap_2_merge.head()

,subject_id,hadm_id,admittime,dischtime,days_until_next_visit,mins_until_next_visit,days_since_last_visit,mins_since_last_visit
0,10000032,22595853,2180-05-06 22:23:00,2180-05-07 17:15:00,50.0,72072.0,-1.0,-1.0
1,10000032,22841357,2180-06-26 18:27:00,2180-06-27 18:49:00,25.0,37066.0,50.0,72072.0
2,10000032,29079034,2180-07-23 12:35:00,2180-07-25 17:55:00,11.0,16189.0,25.0,37066.0
3,10000032,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,-1.0,-1.0,11.0,16189.0
4,10000068,25022803,2160-03-03 23:16:00,2160-03-04 06:26:00,-1.0,-1.0,-1.0,-1.0

In [26]:
dataframe_no_overlap_2_merge.to_csv("/root/MIMICIV/src/dataframe_no_overlap_2_merge.csv", index=False)

In [1]:
import pandas as pd

In [3]:
dataframe_no_overlap_2_merge = pd.read_csv("/root/MIMICIV/src/dataframe_no_overlap_2_merge.csv")
landmark_df_evo_correct = pd.read_csv("/root/MIMICIV/src/landmark_df_evo_correct.csv")

In [ ]:
landmark_df_evo['subject_id'].nunique()  # Check unique patients in landmark dataset<

Landmark_df_evo (the dataset on which we are basing all the analysis) looses 55_037 patients from admissions (after removong the 48 patients). 
We need to investigate starting from the dataset at the base of the landmark_evo dataset what happens.

In [ ]:
mimic_tab_death_visit_evo = pd.read_csv("mimiciv_clinical_dataset_tabular_death_visit_evo.csv")

In [22]:
mimic_tab_death_visit_evo['subject_id'].nunique()

223452

Dataset mimiciv_clinical_dataset_tabular_death_visit_evo.csv has the right number of patients. Then that's good. So, something happend in creating landmark_evo dataset.
Please, refer to the code **check_data_creation_evo.ipynb** for this.

We produced the **landmark_df_evo_correct** which has exactly the same amount of patients of the admissions (it could have been a problem in saving).

In [5]:
landmark_df_evo_correct_no_overlap = landmark_df_evo_correct.merge(dataframe_no_overlap_2_merge, on=['subject_id', 'hadm_id'], how='inner')

In [6]:
landmark_df_evo_correct_no_overlap

,subject_id,hadm_id,admission_category,landmark_visit,age_at_landmark,gender,num_total_visits,death_in_90days,med_text,diag_text,...,proc_per_visit,dose_per_visit,gender_numeric,days_since_previous_visit,admittime,dischtime,days_until_next_visit,mins_until_next_visit,days_since_last_visit,mins_since_last_visit
0,10000032,22595853,EMERGENCY,1,52,F,4,1,Furosemide\nIpratropium Bromide Neb\nPotassium...,Portal hypertension\nOther ascites\nCirrhosis ...,...,{1: ['Percutaneous abdominal drainage']},{1: ['40 mg of Furosemide in TAB through PO/NG...,0,-1.0,2180-05-06 22:23:00,2180-05-07 17:15:00,50.0,72072.0,-1.0,-1.0
1,10000032,22841357,EMERGENCY,2,52,F,4,1,Furosemide\nIpratropium Bromide Neb\nPotassium...,Portal hypertension\nOther ascites\nCirrhosis ...,...,"{1: ['Percutaneous abdominal drainage'], 2: ['...",{1: ['40 mg of Furosemide in TAB through PO/NG...,0,50.0,2180-06-26 18:27:00,2180-06-27 18:49:00,25.0,37066.0,50.0,72072.0
2,10000032,29079034,EMERGENCY,3,52,F,4,1,Furosemide\nIpratropium Bromide Neb\nPotassium...,Portal hypertension\nOther ascites\nCirrhosis ...,...,"{1: ['Percutaneous abdominal drainage'], 2: ['...",{1: ['40 mg of Furosemide in TAB through PO/NG...,0,25.0,2180-07-23 12:35:00,2180-07-25 17:55:00,11.0,16189.0,25.0,37066.0
3,10000032,25742920,EMERGENCY,4,52,F,4,1,Furosemide\nIpratropium Bromide Neb\nPotassium...,Portal hypertension\nOther ascites\nCirrhosis ...,...,"{1: ['Percutaneous abdominal drainage'], 2: ['...",{1: ['40 mg of Furosemide in TAB through PO/NG...,0,11.0,2180-08-05 23:44:00,2180-08-07 17:50:00,-1.0,-1.0,11.0,16189.0
4,10000068,25022803,NORMAL,1,19,F,1,0,NaN,"Alcohol abuse, unspecified",...,{1: ['Other nonoperative respiratory measureme...,{1: ['']},0,-1.0,2160-03-03 23:16:00,2160-03-04 06:26:00,-1.0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544973,19999828,29734428,EMERGENCY,1,46,F,2,0,Magnesium Sulfate\nTopiramate (Topamax)\nBag\n...,Disruption of external operation (surgical) wo...,...,{1: ['Replacement of Abdomen Skin with Autolog...,{1: ['2 gm of Magnesium Sulfate in BAG through...,0,-1.0,2147-07-18 16:23:00,2147-08-04 18:10:00,522.0,753034.0,-1.0,-1.0
544974,19999828,25744818,EMERGENCY,2,48,F,2,0,Magnesium Sulfate\nTopiramate (Topamax)\nBag\n...,Disruption of external operation (surgical) wo...,...,{1: ['Replacement of Abdomen Skin with Autolog...,{1: ['2 gm of Magnesium Sulfate in BAG through...,0,522.0,2149-01-08 16:44:00,2149-01-18 17:00:00,-1.0,-1.0,522.0,753034.0
544975,19999840,26071774,EMERGENCY,1,58,M,2,1,NS\nLeVETiracetam\nMetoprolol Tartrate\nAcetam...,"Cerebral artery occlusion, unspecified with ce...",...,{1: ['Magnetic resonance imaging of brain and ...,"{1: ['500 mL of NS in mL through IV', '1500 mg...",1,-1.0,2164-07-25 00:27:00,2164-07-28 12:15:00,44.0,63452.0,-1.0,-1.0
544976,19999840,21033226,EMERGENCY,2,58,M,2,1,NS\nLeVETiracetam\nMetoprolol Tartrate\nAcetam...,"Cerebral artery occlusion, unspecified with ce...",...,{1: ['Magnetic resonance imaging of brain and ...,"{1: ['500 mL of NS in mL through IV', '1500 mg...",1,44.0,2164-09-10 13:47:00,2164-09-17 13:42:00,-1.0,-1.0,44.0,63452.0
544977,19999987,23865745,EMERGENCY,1,57,F,1,0,Racepinephrine\nIso-Osmotic Dextrose\nVancomyc...,Intracerebral hemorrhage\nCerebral edema\nOthe...,...,"{1: ['Arteriography of cerebral arteries', 'Co...",{1: ['0.5 mL of Racepinephrine in NEB through ...,0,-1.0,2145-11-02 21:38:00,2145-11-11 12:57:00,-1.0,-1.0,-1.0,-1.0

In [7]:
landmark_df_evo_correct_no_overlap['subject_id'].nunique()

223404

Now let's test whether the full prompting scheme works here. There is a problem: few patients are readmitted almost at the same time of dischargment of the previous visit. What to do? The easy approach is to force also for them 1 day-delay (in this case 1 day will be the smallest time unit). Another possible approach would be to go to minutes/seconds in such cases. Howevere there are also cases where the patient gets admitted exactly at the same time of discharge.

In [8]:
landmark_df_evo_correct_no_overlap['days_since_last_visit'] = landmark_df_evo_correct_no_overlap['days_since_last_visit'].replace(0, 1)

In [9]:
import numpy as np

In [10]:
landmark_df_evo_correct_no_overlap['days_since_last_visit_cumulate'] = landmark_df_evo_correct_no_overlap.groupby('subject_id')['days_since_last_visit'].transform(lambda x: [list(x[:i+1]) for i in range(len(x))])
landmark_df_evo_correct_no_overlap['days_since_last_visit_cumulate_sum'] = landmark_df_evo_correct_no_overlap['days_since_last_visit_cumulate'].apply(lambda x: np.cumsum([y for y in x if y > 0][::-1])[::-1] if isinstance(x, list) else [-1])

In [11]:
landmark_df_evo_correct_no_overlap

,subject_id,hadm_id,admission_category,landmark_visit,age_at_landmark,gender,num_total_visits,death_in_90days,med_text,diag_text,...,gender_numeric,days_since_previous_visit,admittime,dischtime,days_until_next_visit,mins_until_next_visit,days_since_last_visit,mins_since_last_visit,days_since_last_visit_cumulate,days_since_last_visit_cumulate_sum
0,10000032,22595853,EMERGENCY,1,52,F,4,1,Furosemide\nIpratropium Bromide Neb\nPotassium...,Portal hypertension\nOther ascites\nCirrhosis ...,...,0,-1.0,2180-05-06 22:23:00,2180-05-07 17:15:00,50.0,72072.0,-1.0,-1.0,[-1.0],[]
1,10000032,22841357,EMERGENCY,2,52,F,4,1,Furosemide\nIpratropium Bromide Neb\nPotassium...,Portal hypertension\nOther ascites\nCirrhosis ...,...,0,50.0,2180-06-26 18:27:00,2180-06-27 18:49:00,25.0,37066.0,50.0,72072.0,"[-1.0, 50.0]",[50.0]
2,10000032,29079034,EMERGENCY,3,52,F,4,1,Furosemide\nIpratropium Bromide Neb\nPotassium...,Portal hypertension\nOther ascites\nCirrhosis ...,...,0,25.0,2180-07-23 12:35:00,2180-07-25 17:55:00,11.0,16189.0,25.0,37066.0,"[-1.0, 50.0, 25.0]","[75.0, 25.0]"
3,10000032,25742920,EMERGENCY,4,52,F,4,1,Furosemide\nIpratropium Bromide Neb\nPotassium...,Portal hypertension\nOther ascites\nCirrhosis ...,...,0,11.0,2180-08-05 23:44:00,2180-08-07 17:50:00,-1.0,-1.0,11.0,16189.0,"[-1.0, 50.0, 25.0, 11.0]","[86.0, 36.0, 11.0]"
4,10000068,25022803,NORMAL,1,19,F,1,0,NaN,"Alcohol abuse, unspecified",...,0,-1.0,2160-03-03 23:16:00,2160-03-04 06:26:00,-1.0,-1.0,-1.0,-1.0,[-1.0],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544973,19999828,29734428,EMERGENCY,1,46,F,2,0,Magnesium Sulfate\nTopiramate (Topamax)\nBag\n...,Disruption of external operation (surgical) wo...,...,0,-1.0,2147-07-18 16:23:00,2147-08-04 18:10:00,522.0,753034.0,-1.0,-1.0,[-1.0],[]
544974,19999828,25744818,EMERGENCY,2,48,F,2,0,Magnesium Sulfate\nTopiramate (Topamax)\nBag\n...,Disruption of external operation (surgical) wo...,...,0,522.0,2149-01-08 16:44:00,2149-01-18 17:00:00,-1.0,-1.0,522.0,753034.0,"[-1.0, 522.0]",[522.0]
544975,19999840,26071774,EMERGENCY,1,58,M,2,1,NS\nLeVETiracetam\nMetoprolol Tartrate\nAcetam...,"Cerebral artery occlusion, unspecified with ce...",...,1,-1.0,2164-07-25 00:27:00,2164-07-28 12:15:00,44.0,63452.0,-1.0,-1.0,[-1.0],[]
544976,19999840,21033226,EMERGENCY,2,58,M,2,1,NS\nLeVETiracetam\nMetoprolol Tartrate\nAcetam...,"Cerebral artery occlusion, unspecified with ce...",...,1,44.0,2164-09-10 13:47:00,2164-09-17 13:42:00,-1.0,-1.0,44.0,63452.0,"[-1.0, 44.0]",[44.0]
544977,19999987,23865745,EMERGENCY,1,57,F,1,0,Racepinephrine\nIso-Osmotic Dextrose\nVancomyc...,Intracerebral hemorrhage\nCerebral edema\nOthe...,...,0,-1.0,2145-11-02 21:38:00,2145-11-11 12:57:00,-1.0,-1.0,-1.0,-1.0,[-1.0],[]

In [12]:
visit_counts = landmark_df_evo_correct_no_overlap['subject_id'].value_counts()
selected_patients = visit_counts[visit_counts == 3].index
landmark_df_evo_correct_no_overlap_selected = landmark_df_evo_correct_no_overlap[landmark_df_evo_correct_no_overlap['subject_id'].isin(selected_patients)].copy()

In [13]:
landmark_df_evo_correct_no_overlap_selected

,subject_id,hadm_id,admission_category,landmark_visit,age_at_landmark,gender,num_total_visits,death_in_90days,med_text,diag_text,...,gender_numeric,days_since_previous_visit,admittime,dischtime,days_until_next_visit,mins_until_next_visit,days_since_last_visit,mins_since_last_visit,days_since_last_visit_cumulate,days_since_last_visit_cumulate_sum
22,10000826,20032235,EMERGENCY,1,32,F,3,0,Morphine Sulfate\nLorazepam\nHeparin\nDocusate...,"Alcoholic cirrhosis of liver\nPneumonia, organ...",...,0,-1.0,2146-12-05 19:07:00,2146-12-12 16:30:00,6.0,8709.0,-1.0,-1.0,[-1.0],[]
23,10000826,21086876,EMERGENCY,2,32,F,3,0,Morphine Sulfate\nLorazepam\nHeparin\nDocusate...,"Alcoholic cirrhosis of liver\nPneumonia, organ...",...,0,6.0,2146-12-18 17:39:00,2146-12-24 19:55:00,6.0,8928.0,6.0,8709.0,"[-1.0, 6.0]",[6.0]
24,10000826,28289260,EMERGENCY,3,32,F,3,0,Morphine Sulfate\nLorazepam\nHeparin\nDocusate...,"Alcoholic cirrhosis of liver\nPneumonia, organ...",...,0,6.0,2146-12-31 00:43:00,2147-01-02 17:45:00,-1.0,-1.0,6.0,8928.0,"[-1.0, 6.0, 6.0]","[12.0, 6.0]"
44,10001186,24906418,EMERGENCY,1,46,F,3,0,Sodium Chloride 0.9% Flush\nOndansetron\nGuai...,Disruption of external operation (surgical) wo...,...,0,-1.0,2188-09-24 15:33:00,2188-09-26 14:40:00,23.0,34115.0,-1.0,-1.0,[-1.0],[]
45,10001186,24016413,NORMAL,2,46,F,3,0,Sodium Chloride 0.9% Flush\nOndansetron\nGuai...,Disruption of external operation (surgical) wo...,...,0,23.0,2188-10-20 07:15:00,2188-10-21 15:05:00,635.0,915370.0,23.0,34115.0,"[-1.0, 23.0]",[23.0]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544914,19999043,24799384,NORMAL,2,35,F,3,0,OxyCODONE (Immediate Release)\nFerrous Sulfate...,(Induced) termination of pregnancy with other ...,...,0,50.0,2164-12-18 22:42:00,2164-12-24 12:45:00,161.0,231991.0,50.0,72279.0,"[-1.0, 50.0]",[50.0]
544915,19999043,21756272,NORMAL,3,36,F,3,0,OxyCODONE (Immediate Release)\nFerrous Sulfate...,(Induced) termination of pregnancy with other ...,...,0,161.0,2165-06-03 15:16:00,2165-06-04 12:55:00,-1.0,-1.0,161.0,231991.0,"[-1.0, 50.0, 161.0]","[211.0, 161.0]"
544926,19999287,25875727,NORMAL,1,71,F,3,1,SW\nMagnesium Sulfate\nPantoprazole\nHYDROmorp...,"Malignant neoplasm of upper lobe, bronchus or ...",...,0,-1.0,2191-12-29 07:15:00,2192-01-11 19:00:00,2022.0,2912189.0,-1.0,-1.0,[-1.0],[]
544927,19999287,22997012,EMERGENCY,2,77,F,3,1,SW\nMagnesium Sulfate\nPantoprazole\nHYDROmorp...,"Malignant neoplasm of upper lobe, bronchus or ...",...,0,2022.0,2197-07-26 03:29:00,2197-07-31 14:00:00,3.0,4738.0,2022.0,2912189.0,"[-1.0, 2022.0]",[2022.0]
544928,19999287,20175828,EMERGENCY,3,77,F,3,1,SW\nMagnesium Sulfate\nPantoprazole\nHYDROmorp...,"Malignant neoplasm of upper lobe, bronchus or ...",...,0,3.0,2197-08-03 20:58:00,2197-08-18 15:37:00,-1.0,-1.0,3.0,4738.0,"[-1.0, 2022.0, 3.0]","[2025.0, 3.0]"

In [14]:
import ast
import random
from collections import Counter

def full_narrative(row):
    narrative = f"You are a Doctor.\nWhat is the probability of death in the next 90 days from today for this {row['age_at_landmark']}-year-old {row['gender']} patient?\n"
    current_visit = row['landmark_visit']
    narrative += f"Today is the {current_visit} visit.\n"

    max_visit = int(row['landmark_visit'])

    # if row['days_since_previous_visit'] != -1:
    #     narrative += f"Last visit happened {row['days_since_previous_visit']} days ago."

    narrative += "\nDiagnosis history:"
    for past_visit, diags in reversed(list(ast.literal_eval(row['diag_per_visit']).items())):
        if past_visit == max_visit:
            narrative += f"\nToday: {'; '.join(diags)}."
        else:
            narrative += f"\n{int(row['days_since_last_visit_cumulate_sum'][int(past_visit) -1])} days ago: {'; '.join(diags)}."

    narrative += "\nPrescriptions history:"
    for past_visit, meds in reversed(ast.literal_eval(row['meds_per_visit']).items()):
        if past_visit ==  max_visit:
            narrative += f"\nToday: {'; '.join(meds)}."
        else:
            narrative += f"\n{int(row['days_since_last_visit_cumulate_sum'][past_visit-1])} days ago: {'; '.join(meds)}."

    narrative += "\nProcedures history:"
    for past_visit, proc in reversed(ast.literal_eval(row['proc_per_visit']).items()):
        if past_visit == max_visit:
            narrative += f"\nToday: {'; '.join(proc)}."
        else:
            narrative += f"\n{int(row['days_since_last_visit_cumulate_sum'][past_visit-1])} days ago: {'; '.join(proc)}."
    
    return narrative

def full_narrative_no_time_rnd(row):
    narrative = f"You are a Doctor.\nWhat is the probability of death in the next 90 days from today for this {row['age_at_landmark']}-year-old {row['gender']} patient?\n"

    # Diagnosi
    all_diags = []
    diag_dict = ast.literal_eval(row['diag_per_visit'])
    for diags in diag_dict.values():
        all_diags.extend(diags)
    random.shuffle(all_diags)
    narrative += "\nDiagnosis history:\n" + '; '.join(all_diags) + "."

    # Prescrizioni
    all_meds = []
    meds_dict = ast.literal_eval(row['meds_per_visit'])
    for meds in meds_dict.values():
        all_meds.extend(meds)
    random.shuffle(all_meds)
    narrative += "\nPrescriptions history:\n" + '; '.join(all_meds) + "."

    # Procedure
    all_procs = []
    proc_dict = ast.literal_eval(row['proc_per_visit'])
    for procs in proc_dict.values():
        all_procs.extend(procs)
    random.shuffle(all_procs)
    narrative += "\nProcedures history:\n" + '; '.join(all_procs) + "."

    return narrative

def no_narrative_prompt(row):
    narrative = "Variables: "
    if pd.notna(row['diag_text']) and row['diag_text'].strip():
        narrative += f" {row['diag_text']}"
    if pd.notna(row['med_text']) and row['med_text'].strip():
        narrative += f" {row['med_text']}"
    if pd.notna(row['proc_text']) and row['proc_text'].strip():
        narrative += f" {row['proc_text']}"

    return narrative

def compact_narrative_prompt(row):
    narrative = f"You are a Doctor.\nWhat is the probability of death in the next 90 days for {row['age_at_landmark']}-year-old {row['gender']} patient?\n"
    current_visit = row['landmark_visit']
    type = row['admission_category']
    narrative += f"Visit number {current_visit} - {type} \n"

    if row['days_since_previous_visit'] != -1:
        narrative += f"Last visit happened {row['days_since_previous_visit']} days ago."

    # --- Diagnosi ---
    narrative += "\nDIAGNOSIS HISTORY:"
    diag_per_visit = ast.literal_eval(row['diag_per_visit'])
    
    # Conta frequenze
    all_diags = []
    for diags in diag_per_visit.values():
        all_diags.extend(diags)
    diag_counts = Counter(all_diags)

    # Diagnosi croniche (almeno 2 visite)
    chronic_diags = [d for d, c in diag_counts.items() if c >= 2]

    # Diagnosi nuove solo in questa visita
    current_diags = diag_per_visit[int(current_visit)]
    new_diags = [d for d in current_diags if diag_counts[d] == 1]

    if chronic_diags:
        narrative += f"\nChronic diagnoses: {'; '.join(chronic_diags)}."
    if new_diags:
        narrative += f"\nNew diagnoses in this visit: {'; '.join(new_diags)}."
    if not chronic_diags and not new_diags:
        narrative += "\nNo diagnoses recorded."

    # --- Farmaci ---
    narrative += "\nPRESCRIPTIONS HISTORY:"
    meds_per_visit = ast.literal_eval(row['meds_per_visit'])
    
    all_meds = []
    for meds in meds_per_visit.values():
        all_meds.extend(meds)
    med_counts = Counter(all_meds)

    chronic_meds = [m for m, c in med_counts.items() if c >= 2]
    current_meds = meds_per_visit[int(current_visit)]
    new_meds = [m for m in current_meds if med_counts[m] == 1]

    if chronic_meds:
        narrative += f"\nChronic medications: {'; '.join(chronic_meds)}."
    if new_meds:
        narrative += f"\nNew medications in this visit: {'; '.join(new_meds)}."
    if not chronic_meds and not new_meds:
        narrative += "\nNo medications recorded."

    # --- Procedure ---
    narrative += "\nPROCEDURES HISTORY:"
    proc_per_visit = ast.literal_eval(row['proc_per_visit'])

    all_proc = []
    for procs in proc_per_visit.values():
        all_proc.extend(procs)
    proc_counts = Counter(all_proc)

    chronic_proc = [p for p, c in proc_counts.items() if c >= 2]
    current_proc = proc_per_visit[int(current_visit)]
    new_proc = [p for p in current_proc if proc_counts[p] == 1]

    if chronic_proc:
        narrative += f"\nChronic procedures: {'; '.join(chronic_proc)}."
    if new_proc:
        narrative += f"\nNew procedures in this visit: {'; '.join(new_proc)}."
    if not chronic_proc and not new_proc:
        narrative += "\nNo procedures recorded."

    return narrative

In [15]:
train_df = landmark_df_evo_correct_no_overlap_selected[landmark_df_evo_correct_no_overlap_selected['landmark_visit'] == 3].copy()

In [16]:
train_df.columns

Index(['subject_id', 'hadm_id', 'admission_category', 'landmark_visit',
       'age_at_landmark', 'gender', 'num_total_visits', 'death_in_90days',
       'med_text', 'diag_text', 'proc_text', 'dose_text', 'new_medications',
       'new_diagnoses', 'new_procedures', 'new_dose', 'no_more_diagnoses',
       'no_more_medications', 'no_more_procedures', 'no_more_dose',
       'meds_per_visit', 'diag_per_visit', 'proc_per_visit', 'dose_per_visit',
       'gender_numeric', 'days_since_previous_visit', 'admittime', 'dischtime',
       'days_until_next_visit', 'mins_until_next_visit',
       'days_since_last_visit', 'mins_since_last_visit',
       'days_since_last_visit_cumulate', 'days_since_last_visit_cumulate_sum'],
      dtype='object')

In [17]:
problem_subjects = train_df[train_df.apply(lambda x: len(x['days_since_last_visit_cumulate_sum'])==0, axis=1)]['subject_id'].reset_index(drop=True).tolist()

In [18]:
landmark_df_evo_correct_no_overlap_selected[landmark_df_evo_correct_no_overlap_selected['subject_id'].isin(problem_subjects)]

Empty DataFrame
Columns: [subject_id, hadm_id, admission_category, landmark_visit, age_at_landmark, gender, num_total_visits, death_in_90days, med_text, diag_text, proc_text, dose_text, new_medications, new_diagnoses, new_procedures, new_dose, no_more_diagnoses, no_more_medications, no_more_procedures, no_more_dose, meds_per_visit, diag_per_visit, proc_per_visit, dose_per_visit, gender_numeric, days_since_previous_visit, admittime, dischtime, days_until_next_visit, mins_until_next_visit, days_since_last_visit, mins_since_last_visit, days_since_last_visit_cumulate, days_since_last_visit_cumulate_sum]
Index: []

[0 rows x 34 columns]

In [19]:
train_texts_full = train_df.apply(full_narrative, axis=1).tolist()
train_texts_full_no_time_rnd = train_df.apply(full_narrative_no_time_rnd, axis=1).tolist()
train_texts_no_narrative = train_df.apply(no_narrative_prompt, axis = 1).tolist()
train_texts_compact = train_df.apply(compact_narrative_prompt, axis = 1).tolist()

In [20]:
print(train_texts_full[12])

You are a Doctor.
What is the probability of death in the next 90 days from today for this 78-year-old M patient?
Today is the 3 visit.

Diagnosis history:
Today: Aortic valve disorders; Mobitz (type) II atrioventricular block; Unspecified pleural effusion; Other B-complex deficiencies; Atrial fibrillation; Thrombocytopenia, unspecified; Pulmonary collapse; Cardiac complications, not elsewhere classified; Coronary atherosclerosis of native coronary artery; Unspecified essential hypertension; Osteoarthrosis, unspecified whether generalized or localized, hand; Depressive disorder, not elsewhere classified; Other and unspecified hyperlipidemia; Iron deficiency anemia, unspecified; Orthostatic hypotension; Unspecified glaucoma; Atherosclerosis of aorta; Degeneration of cervical intervertebral disc; Degeneration of lumbar or lumbosacral intervertebral disc; Surgical operation with implant of artificial internal device causing abnormal patient reaction, or later complication,without mention of misadventure at time of operation; Examination of participant in clinical trial; Personal history of malignant neoplasm of prostate; Personal history of malignant neoplasm of bronchus and lung; Personal history of other malignant neoplasm of skin; Family history of ischemic heart disease; Personal history of tobacco use; Percutaneous transluminal coronary angioplasty status; Personal history of alcoholism.
521 days ago: Coronary atherosclerosis of native coronary artery; Unspecified essential hypertension; Other and unspecified angina pectoris; Other and unspecified hyperlipidemia; Long-term (current) use of aspirin.
772 days ago: Malignant neoplasm of lower lobe, bronchus or lung; Mobitz (type) II atrioventricular block; Loss of weight; Body Mass Index between 19-24, adult; Coronary atherosclerosis of native coronary artery; Percutaneous transluminal coronary angioplasty status; Personal history of malignant neoplasm of prostate; Aortic valve disorders; Cerebral atherosclerosis; Anemia, unspecified; Unspecified essential hypertension; Other and unspecified hyperlipidemia; Impaired glucose tolerance test (oral); Other and unspecified alcohol dependence, in remission; Osteoarthrosis, unspecified whether generalized or localized, hand; Cervical spondylosis without myelopathy; Lumbosacral spondylosis without myelopathy; Depressive disorder, not elsewhere classified; Unspecified glaucoma; Unspecified hereditary and idiopathic peripheral neuropathy; Dysphonia; Personal history of tobacco use; Retention of urine, unspecified; Orthostatic hypotension; Atrial fibrillation; Hypopotassemia; Disorders of phosphorus metabolism; Disorders of magnesium metabolism.
Prescriptions history:
Today: Acetaminophen; Influenza Vaccine Quadrivalent; brimonidine; 5% Dextrose; CefazoLIN; Neostigmine; Sodium Chloride 0.9%  Flush; FoLIC Acid; OxycoDONE (Immediate Release) ; Ranitidine; Metoprolol Tartrate; Lactated Ringers; Milk of Magnesia; Simvastatin; Chlorhexidine Gluconate 0.12% Oral Rinse; Brimonidine Tartrate 0.15% Ophth.; Amiodarone; Atorvastatin; Mupirocin Ointment 2%; Fentanyl Citrate; Latanoprost 0.005% Ophth. Soln.; Insulin; Furosemide; Sterile Water; Potassium Chloride; Aspirin; Glycopyrrolate; Aspirin EC; 0.9% Sodium Chloride; Insulin Human Regular; Warfarin; Acetaminophen IV; Metoclopramide; Glucose Gel; Bag; Magnesium Sulfate; PHENYLEPHrine; Citalopram; SulfaSALAzine_; Docusate Sodium; Dorzolamide 2% Ophth. Soln.; Calcium Gluconate; Syringe; Nitroglycerin; Ferrous Sulfate; Oxycodone-Acetaminophen (5mg-325mg); Propofol; TraMADOL (Ultram); Dextrose 50%; Dextrose 5%; Iso-Osmotic Dextrose; Vancomycin; Glucagon; Multivitamins.
521 days ago: Potassium Chloride; Docusate Sodium; Latanoprost 0.005% Ophth. Soln.; Citalopram; Sodium Chloride 0.9%  Flush; D5 1/2NS; Nitroglycerin SL; Dorzolamide 2% Ophth. Soln.; Atorvastatin; brimonidine; Simethicone; TraZODone; Multivitamins; Atropine Sulfate; Aspirin EC; Acetaminophen; Clopidogrel.
772 days ago: Ketorolac; OxycoDONE (Immediate Release) ; HYDROmorphone (Dilaudid); Citalopram; Sodium Chloride 0.9%  Flush; Dorzolamide 2%/Timolol 0.5% Ophth.; Potassium Chloride; Aspirin; Tamsulosin; traZODONE; Metoprolol Tartrate; Ondansetron; Influenza Virus Vaccine; Bag; Magnesium Sulfate; Bisacodyl; Pantoprazole; Pneumococcal Vac Polyvalent; Magnesium Oxide; Lidocaine Jelly 2% (Urojet); Acetaminophen; 0.9% Sodium Chloride; Potassium Phosphate; Atorvastatin; TraMADOL (Ultram); Latanoprost 0.005% Ophth. Soln.; Milk of Magnesia; Heparin; Albuterol 0.083% Neb Soln; Docusate Sodium; Neutra-Phos; Haloperidol.
Procedures history:
Today: Open and other replacement of aortic valve with tissue graft; Left heart cardiac catheterization; (Aorto)coronary bypass of one coronary artery; Coronary arteriography using two catheters; Extracorporeal circulation auxiliary to open heart surgery; Venous catheterization, not elsewhere classified.
521 days ago: Percutaneous transluminal coronary angioplasty [PTCA]; Insertion of drug-eluting coronary artery stent(s); Insertion of one vascular stent; Coronary arteriography using two catheters; Procedure on two vessels.
772 days ago: Thoracoscopic lobectomy of lung; Regional lymph node excision.

In [21]:
print(train_texts_full_no_time_rnd[12])

You are a Doctor.
What is the probability of death in the next 90 days from today for this 78-year-old M patient?

Diagnosis history:
Osteoarthrosis, unspecified whether generalized or localized, hand; Coronary atherosclerosis of native coronary artery; Degeneration of cervical intervertebral disc; Orthostatic hypotension; Unspecified glaucoma; Percutaneous transluminal coronary angioplasty status; Unspecified glaucoma; Orthostatic hypotension; Other and unspecified hyperlipidemia; Other and unspecified angina pectoris; Personal history of other malignant neoplasm of skin; Depressive disorder, not elsewhere classified; Personal history of malignant neoplasm of prostate; Personal history of tobacco use; Unspecified hereditary and idiopathic peripheral neuropathy; Aortic valve disorders; Personal history of malignant neoplasm of bronchus and lung; Lumbosacral spondylosis without myelopathy; Dysphonia; Coronary atherosclerosis of native coronary artery; Other B-complex deficiencies; Atrial fibrillation; Aortic valve disorders; Mobitz (type) II atrioventricular block; Iron deficiency anemia, unspecified; Disorders of magnesium metabolism; Mobitz (type) II atrioventricular block; Malignant neoplasm of lower lobe, bronchus or lung; Family history of ischemic heart disease; Pulmonary collapse; Percutaneous transluminal coronary angioplasty status; Long-term (current) use of aspirin; Disorders of phosphorus metabolism; Surgical operation with implant of artificial internal device causing abnormal patient reaction, or later complication,without mention of misadventure at time of operation; Unspecified essential hypertension; Osteoarthrosis, unspecified whether generalized or localized, hand; Retention of urine, unspecified; Other and unspecified alcohol dependence, in remission; Unspecified pleural effusion; Other and unspecified hyperlipidemia; Unspecified essential hypertension; Body Mass Index between 19-24, adult; Personal history of alcoholism; Personal history of tobacco use; Other and unspecified hyperlipidemia; Cardiac complications, not elsewhere classified; Atherosclerosis of aorta; Depressive disorder, not elsewhere classified; Atrial fibrillation; Hypopotassemia; Thrombocytopenia, unspecified; Anemia, unspecified; Cervical spondylosis without myelopathy; Loss of weight; Examination of participant in clinical trial; Personal history of malignant neoplasm of prostate; Coronary atherosclerosis of native coronary artery; Degeneration of lumbar or lumbosacral intervertebral disc; Unspecified essential hypertension; Impaired glucose tolerance test (oral); Cerebral atherosclerosis.
Prescriptions history:
Potassium Phosphate; Acetaminophen; Amiodarone; Dorzolamide 2%/Timolol 0.5% Ophth.; Sodium Chloride 0.9%  Flush; HYDROmorphone (Dilaudid); Bisacodyl; Potassium Chloride; Influenza Virus Vaccine; Latanoprost 0.005% Ophth. Soln.; Warfarin; SulfaSALAzine_; Oxycodone-Acetaminophen (5mg-325mg); Latanoprost 0.005% Ophth. Soln.; OxycoDONE (Immediate Release) ; Potassium Chloride; Ondansetron; Aspirin EC; Syringe; TraZODone; Acetaminophen IV; Docusate Sodium; OxycoDONE (Immediate Release) ; Milk of Magnesia; Multivitamins; Dextrose 50%; Ketorolac; Simethicone; Pantoprazole; Propofol; Citalopram; traZODONE; Acetaminophen; Acetaminophen; PHENYLEPHrine; Aspirin EC; Magnesium Sulfate; TraMADOL (Ultram); 0.9% Sodium Chloride; Milk of Magnesia; Dextrose 5%; Sterile Water; Clopidogrel; Sodium Chloride 0.9%  Flush; Metoprolol Tartrate; TraMADOL (Ultram); Atorvastatin; Metoclopramide; brimonidine; Nitroglycerin SL; Iso-Osmotic Dextrose; Lidocaine Jelly 2% (Urojet); Glucose Gel; CefazoLIN; Docusate Sodium; Furosemide; 0.9% Sodium Chloride; Simvastatin; Magnesium Sulfate; Potassium Chloride; Sodium Chloride 0.9%  Flush; Insulin Human Regular; Neostigmine; Latanoprost 0.005% Ophth. Soln.; Aspirin; Dorzolamide 2% Ophth. Soln.; Haloperidol; Ferrous Sulfate; Mupirocin Ointment 2%; Neutra-Phos; Insulin; Docusate Sodium; Calcium Gluconate; D5 1/2NS; Atropine Sulfate; Glycopyrrolate; Heparin; Pneumococcal Vac Polyvalent; Metoprolol Tartrate; Magnesium Oxide; Dorzolamide 2% Ophth. Soln.; Lactated Ringers; FoLIC Acid; Citalopram; Aspirin; Atorvastatin; Bag; Multivitamins; brimonidine; Citalopram; Bag; Tamsulosin; Atorvastatin; Vancomycin; Albuterol 0.083% Neb Soln; Influenza Vaccine Quadrivalent; 5% Dextrose; Chlorhexidine Gluconate 0.12% Oral Rinse; Brimonidine Tartrate 0.15% Ophth.; Nitroglycerin; Fentanyl Citrate; Ranitidine; Glucagon.
Procedures history:
Left heart cardiac catheterization; Procedure on two vessels; Thoracoscopic lobectomy of lung; Coronary arteriography using two catheters; Regional lymph node excision; Venous catheterization, not elsewhere classified; Insertion of one vascular stent; Insertion of drug-eluting coronary artery stent(s); Extracorporeal circulation auxiliary to open heart surgery; Coronary arteriography using two catheters; Open and other replacement of aortic valve with tissue graft; Percutaneous transluminal coronary angioplasty [PTCA]; (Aorto)coronary bypass of one coronary artery.

In [22]:
print(train_texts_no_narrative[12])

Variables:  Malignant neoplasm of lower lobe, bronchus or lung
Mobitz (type) II atrioventricular block
Loss of weight
Body Mass Index between 19-24, adult
Coronary atherosclerosis of native coronary artery
Percutaneous transluminal coronary angioplasty status
Personal history of malignant neoplasm of prostate
Aortic valve disorders
Cerebral atherosclerosis
Anemia, unspecified
Unspecified essential hypertension
Other and unspecified hyperlipidemia
Impaired glucose tolerance test (oral)
Other and unspecified alcohol dependence, in remission
Osteoarthrosis, unspecified whether generalized or localized, hand
Cervical spondylosis without myelopathy
Lumbosacral spondylosis without myelopathy
Depressive disorder, not elsewhere classified
Unspecified glaucoma
Unspecified hereditary and idiopathic peripheral neuropathy
Dysphonia
Personal history of tobacco use
Retention of urine, unspecified
Orthostatic hypotension
Atrial fibrillation
Hypopotassemia
Disorders of phosphorus metabolism
Disorders of magnesium metabolism
Coronary atherosclerosis of native coronary artery
Unspecified essential hypertension
Other and unspecified angina pectoris
Other and unspecified hyperlipidemia
Long-term (current) use of aspirin
Aortic valve disorders
Mobitz (type) II atrioventricular block
Unspecified pleural effusion
Other B-complex deficiencies
Atrial fibrillation
Thrombocytopenia, unspecified
Pulmonary collapse
Cardiac complications, not elsewhere classified
Coronary atherosclerosis of native coronary artery
Unspecified essential hypertension
Osteoarthrosis, unspecified whether generalized or localized, hand
Depressive disorder, not elsewhere classified
Other and unspecified hyperlipidemia
Iron deficiency anemia, unspecified
Orthostatic hypotension
Unspecified glaucoma
Atherosclerosis of aorta
Degeneration of cervical intervertebral disc
Degeneration of lumbar or lumbosacral intervertebral disc
Surgical operation with implant of artificial internal device causing abnormal patient reaction, or later complication,without mention of misadventure at time of operation
Examination of participant in clinical trial
Personal history of malignant neoplasm of prostate
Personal history of malignant neoplasm of bronchus and lung
Personal history of other malignant neoplasm of skin
Family history of ischemic heart disease
Personal history of tobacco use
Percutaneous transluminal coronary angioplasty status
Personal history of alcoholism Ketorolac
OxycoDONE (Immediate Release)
HYDROmorphone (Dilaudid)
Citalopram
Sodium Chloride 0.9%  Flush
Dorzolamide 2%/Timolol 0.5% Ophth.
Potassium Chloride
Aspirin
Tamsulosin
traZODONE
Metoprolol Tartrate
Ondansetron
Influenza Virus Vaccine
Bag
Magnesium Sulfate
Bisacodyl
Pantoprazole
Pneumococcal Vac Polyvalent
Magnesium Oxide
Lidocaine Jelly 2% (Urojet)
Acetaminophen
0.9% Sodium Chloride
Potassium Phosphate
Atorvastatin
TraMADOL (Ultram)
Latanoprost 0.005% Ophth. Soln.
Milk of Magnesia
Heparin
Albuterol 0.083% Neb Soln
Docusate Sodium
Neutra-Phos
Haloperidol
Potassium Chloride
Docusate Sodium
Latanoprost 0.005% Ophth. Soln.
Citalopram
Sodium Chloride 0.9%  Flush
D5 1/2NS
Nitroglycerin SL
Dorzolamide 2% Ophth. Soln.
Atorvastatin
brimonidine
Simethicone
TraZODone
Multivitamins
Atropine Sulfate
Aspirin EC
Acetaminophen
Clopidogrel
Acetaminophen
Influenza Vaccine Quadrivalent
brimonidine
5% Dextrose
CefazoLIN
Neostigmine
Sodium Chloride 0.9%  Flush
FoLIC Acid
OxycoDONE (Immediate Release)
Ranitidine
Metoprolol Tartrate
Lactated Ringers
Milk of Magnesia
Simvastatin
Chlorhexidine Gluconate 0.12% Oral Rinse
Brimonidine Tartrate 0.15% Ophth.
Amiodarone
Atorvastatin
Mupirocin Ointment 2%
Fentanyl Citrate
Latanoprost 0.005% Ophth. Soln.
Insulin
Furosemide
Sterile Water
Potassium Chloride
Aspirin
Glycopyrrolate
Aspirin EC
0.9% Sodium Chloride
Insulin Human Regular
Warfarin
Acetaminophen IV
Metoclopramide
Glucose Gel
Bag
Magnesium Sulfate
PHENYLEPHrine
Citalopram
SulfaSALAzine_
Docusate Sodium
Dorzolamide 2% Ophth. Soln.
Calcium Gluconate
Syringe
Nitroglycerin
Ferrous Sulfate
Oxycodone-Acetaminophen (5mg-325mg)
Propofol
TraMADOL (Ultram)
Dextrose 50%
Dextrose 5%
Iso-Osmotic Dextrose
Vancomycin
Glucagon
Multivitamins 15 mg of Ketorolac in VIAL through IV
5-10 mg of OxycoDONE (Immediate Release)  in TAB through PO/NG
0.5-1 mg of HYDROmorphone (Dilaudid) in SYR through IV
20 mg of Citalopram in TAB through PO/NG
3 mL of Sodium Chloride 0.9%  Flush in SYR through IV
1 DROP of Dorzolamide 2%/Timolol 0.5% Ophth. in DBTL through LEFT EYE
40 mEq of Potassium Chloride in PKT through PO
325 mg of Aspirin in TAB through PO/NG
0.4 mg of Tamsulosin in CAP through PO
50 mg of traZODONE in TAB through PO/NG
25 mg of Metoprolol Tartrate in TAB through PO
4 mg of Ondansetron in VIAL through IV
0.5 mL of Influenza Virus Vaccine in SYR through IM
50 mL of Bag in BAG through IV
2 gm of Magnesium Sulfate in BAG through IV
10 mg of Bisacodyl in SUPP through PR
40 mg of Pantoprazole in TAB through PO
0.5 mL of Pneumococcal Vac Polyvalent in VIAL through IM
400 mg of Magnesium Oxide in TAB through PO/NG
1 Appl of Lidocaine Jelly 2% (Urojet) in TUBE through TP
650 mg of Acetaminophen in TAB through PO/NG
500 mL of 0.9% Sodium Chloride in mL through IV
30 mmol of Potassium Phosphate in mL through IV
80 mg of Atorvastatin in TAB through PO/NG
1000 mL of 0.9% Sodium Chloride in mL through IV
12.5 mg of Metoprolol Tartrate in TAB through PO/NG
0.5-1 mg of HYDROmorphone (Dilaudid) in SYR through IV
50 mg of traZODONE in TAB through PO/NG
5 mg of Metoprolol Tartrate in VIAL through IV
500 mL of 0.9% Sodium Chloride in mL through IV
30 mmol of Potassium Phosphate in mL through IV
40 mEq of Potassium Chloride in TAB through PO
50 mg of TraMADOL (Ultram) in TAB through PO
5 mg of Metoprolol Tartrate in VIAL through IV
1 Appl of Lidocaine Jelly 2% (Urojet) in TUBE through TP
40 mEq of Potassium Chloride in TAB through PO
25 mg of Metoprolol Tartrate in TAB through PO/NG
2-4 mg of HYDROmorphone (Dilaudid) in TAB through PO
1 DROP of Latanoprost 0.005% Ophth. Soln. in DBTL through LEFT EYE
5 mg of Metoprolol Tartrate in VIAL through IV
30 mL of Milk of Magnesia in UDCUP through PO/NG
5000 UNIT of Heparin in mL through SC
1 NEB of Albuterol 0.083% Neb Soln in VIAL through IH
100 mg of Docusate Sodium in CAP through PO/NG
10 mg of Bisacodyl in TAB through PO
1 PKT of Neutra-Phos in PKT through PO/NG
0.25 mg of Haloperidol in VIAL through IV
5000 UNIT of Heparin in mL through SC
50 mg of Metoprolol Tartrate in TAB through PO/NG
12.5 mg of Metoprolol Tartrate in TAB through PO/NG
4-6 mg of HYDROmorphone (Dilaudid) in TAB through PO
40 mEq of Potassium Chloride in PKT through PO
100 mg of Docusate Sodium in CAP through PO/NG
60 mEq of Potassium Chloride in PKT through PO
1 DROP of Latanoprost 0.005% Ophth. Soln. in DBTL through LEFT EYE
20 mg of Citalopram in TAB through PO/NG
3 mL of Sodium Chloride 0.9%  Flush in SYR through IV
1000 mL of D5 1/2NS in mL through IV
0.3 mg of Nitroglycerin SL in TAB through SL
1 DROP of Dorzolamide 2% Ophth. Soln. in DBTL through LEFT EYE
80 mg of Atorvastatin in TAB through PO/NG
1 gtt of brimonidine in DBTL through OS
40-80 mg of Simethicone in TAB through PO/NG
25 mg of TraZODone in TAB through PO/NG
1 TAB of Multivitamins in TAB through PO/NG
0.5 mg of Atropine Sulfate in SYR through IV
20 mEq of Potassium Chloride in PKT through PO
325 mg of Aspirin EC in TAB through PO
650 mg of Acetaminophen in TAB through PO/NG
75 mg of Clopidogrel in TAB through PO
650 mg of Acetaminophen in SUPP through PR
0.5 mL of Influenza Vaccine Quadrivalent in SYR through IM
0.2 % of brimonidine in DBTL through LEFT EYE
100 mL of 5% Dextrose in mL through IV
2 g of CefazoLIN in g through IV
3 mg of Neostigmine in VIAL through IV
0.15 % of brimonidine in DBTL through LEFT EYE
10 mL of Sodium Chloride 0.9%  Flush in SYR through IV
1 mg of FoLIC Acid in TAB through PO/NG
5-10 mg of OxycoDONE (Immediate Release)  in UDCUP through PO/NG
150 mg of Ranitidine in TAB through PO/NG
12.5 mg of Metoprolol Tartrate in HALF TAB through PO/NG
1000 mL of Lactated Ringers in BAG through IV
30 mL of Milk of Magnesia in UDCUP through PO
20 mg of Simvastatin in TAB through PO/NG
15 mL of Chlorhexidine Gluconate 0.12% Oral Rinse in UDCUP through ORAL
1 DROP of Brimonidine Tartrate 0.15% Ophth. in DBTL through LEFT EYE
150 mg of Amiodarone in mg through IV
25 mg of Metoprolol Tartrate in HALF TAB through PO/NG
40 mg of Atorvastatin in TAB through PO/NG
1 Appl of Mupirocin Ointment 2% in TUBE through NU
12.5-25 mcg of Fentanyl Citrate in mL through IV
1 DROP of Latanoprost 0.005% Ophth. Soln. in DBTL through BOTH EYES
1 DROP of Latanoprost 0.005% Ophth. Soln. in DBTL through BOTH EYES
25 mg of Metoprolol Tartrate in TAB through PO/NG
100 mL of 5% Dextrose in mL through IV
2 g of CefazoLIN in g through IV
25 mg of Metoprolol Tartrate in TAB through PO/NG
0 UNIT of Insulin in mL through SC
20 mg of Furosemide in VIAL through IV
50 mL of Sterile Water in mL through IV
20 mEq of Potassium Chloride in mL through IV
50 mg of Metoprolol Tartrate in TAB through PO/NG
81 mg of Aspirin in TAB through NG
0.6 mg of Glycopyrrolate in VIAL through IV
12.5 mg of Metoprolol Tartrate in TAB through PO/NG
3 mL of Sodium Chloride 0.9%  Flush in SYR through IV
650 mg of Acetaminophen in UDCUP through PO
81 mg of Aspirin EC in TAB through PO
100 mL of 0.9% Sodium Chloride in mL through IV DRIP
100 UNIT of Insulin Human Regular in mL through IV DRIP
5-10 mg of OxycoDONE (Immediate Release)  in TAB through PO/NG
325 mg of Aspirin in TAB through PO/NG
2 mg of Warfarin in TAB through PO/NG
37.5 mg of Metoprolol Tartrate in HALF TAB through PO/NG
1000 mg of Acetaminophen IV in VIAL through IV
10 mg of Metoclopramide in VIAL through IV
5 mg of Warfarin in TAB through PO/NG
0 UNIT of Insulin in mL through SC
15 g of Glucose Gel in TUBE through PO
1 BAG of Bag in BAG through IV
2 gm of Magnesium Sulfate in BAG through IV
250 mL of 5% Dextrose in mL through IV DRIP
60 mg of PHENYLEPHrine in VIAL through IV DRIP
0.5 mL of Influenza Vaccine Quadrivalent in SYR through IM
25 mg of Metoprolol Tartrate in TAB through PO/NG
1 mg of FoLIC Acid in TAB through PO/NG
20 mg of Citalopram in TAB through PO/NG
500 mg of SulfaSALAzine_ in TAB through PO/NG
150 mg of Ranitidine in UDCUP through PO/NG
100 mg of Docusate Sodium in UDCUP through PO/NG
12.5 mg of Metoprolol Tartrate in HALF TAB through PO/NG
650 mg of Acetaminophen in SUPP through PR
1 DROP of Dorzolamide 2% Ophth. Soln. in DBTL through LEFT EYE
1 Appl of Mupirocin Ointment 2% in TUBE through NU
20 mg of Simvastatin in TAB through PO/NG
1 BAG of 0.9% Sodium Chloride in BAG through IV
2 g of Calcium Gluconate in BAG through IV
20 mL of Syringe in SYR through IV DRIP
8 mg of Nitroglycerin in SYR through IV DRIP
40 mEq of Potassium Chloride in TAB through PO
3 mL of Sodium Chloride 0.9%  Flush in SYR through IV
650 mg of Acetaminophen in TAB through PO
325 mg of Ferrous Sulfate in TAB through PO/NG
100 mg of Docusate Sodium in CAP through PO/NG
500-1000 mg of Acetaminophen in TAB through PO/NG
12.5 mg of Metoprolol Tartrate in HALF TAB through PO/NG
1-2 TAB of Oxycodone-Acetaminophen (5mg-325mg) in TAB through PO
1000 mg of Propofol in VIAL through IV DRIP
50 mg of TraMADOL (Ultram) in TAB through PO
1 DROP of Dorzolamide 2% Ophth. Soln. in DBTL through LEFT EYE
20 mg of Citalopram in TAB through PO/NG
20 mEq of Potassium Chloride in TAB through PO
1 dose of Warfarin in dose through PO/NG
650 mg of Acetaminophen in TAB through PO
12.5 gm of Dextrose 50% in SYR through IV
1000 mL of Dextrose 5% in mL through IV
1 SYR of Syringe in SYR through IV DRIP
12 mg of PHENYLEPHrine in SYR through IV DRIP
1 mL of Bag in BAG through IV
2 gm of Magnesium Sulfate in BAG through IV
100 mg of Docusate Sodium in UDCUP through PO/NG
40 mEq of Potassium Chloride in TAB through PO
200 mL of Iso-Osmotic Dextrose in mL through IV
1000 mg of Vancomycin in BAG through IV
100 mg of Docusate Sodium in CAP through PO/NG
1 mg of Glucagon in VIAL through IM
1 TAB of Multivitamins in TAB through PO/NG
20 UNIT of Insulin in VIAL through SC
500 mg of SulfaSALAzine_ in TAB through PO/NG

In [23]:
print(train_texts_compact[12])

You are a Doctor.
What is the probability of death in the next 90 days for 78-year-old M patient?
Visit number 3 - EMERGENCY
Last visit happened 521.0 days ago.
DIAGNOSIS HISTORY:
Chronic diagnoses: Mobitz (type) II atrioventricular block; Coronary atherosclerosis of native coronary artery; Percutaneous transluminal coronary angioplasty status; Personal history of malignant neoplasm of prostate; Aortic valve disorders; Unspecified essential hypertension; Other and unspecified hyperlipidemia; Osteoarthrosis, unspecified whether generalized or localized, hand; Depressive disorder, not elsewhere classified; Unspecified glaucoma; Personal history of tobacco use; Orthostatic hypotension; Atrial fibrillation.
New diagnoses in this visit: Unspecified pleural effusion; Other B-complex deficiencies; Thrombocytopenia, unspecified; Pulmonary collapse; Cardiac complications, not elsewhere classified; Iron deficiency anemia, unspecified; Atherosclerosis of aorta; Degeneration of cervical intervertebral disc; Degeneration of lumbar or lumbosacral intervertebral disc; Surgical operation with implant of artificial internal device causing abnormal patient reaction, or later complication,without mention of misadventure at time of operation; Examination of participant in clinical trial; Personal history of malignant neoplasm of bronchus and lung; Personal history of other malignant neoplasm of skin; Family history of ischemic heart disease; Personal history of alcoholism.
PRESCRIPTIONS HISTORY:
Chronic medications: OxycoDONE (Immediate Release) ; Citalopram; Sodium Chloride 0.9%  Flush; Potassium Chloride; Aspirin; Metoprolol Tartrate; Bag; Magnesium Sulfate; Acetaminophen; 0.9% Sodium Chloride; Atorvastatin; TraMADOL (Ultram); Latanoprost 0.005% Ophth. Soln.; Milk of Magnesia; Docusate Sodium; Dorzolamide 2% Ophth. Soln.; brimonidine; Multivitamins; Aspirin EC.
New medications in this visit: Influenza Vaccine Quadrivalent; 5% Dextrose; CefazoLIN; Neostigmine; FoLIC Acid; Ranitidine; Lactated Ringers; Simvastatin; Chlorhexidine Gluconate 0.12% Oral Rinse; Brimonidine Tartrate 0.15% Ophth.; Amiodarone; Mupirocin Ointment 2%; Fentanyl Citrate; Insulin; Furosemide; Sterile Water; Glycopyrrolate; Insulin Human Regular; Warfarin; Acetaminophen IV; Metoclopramide; Glucose Gel; PHENYLEPHrine; SulfaSALAzine_; Calcium Gluconate; Syringe; Nitroglycerin; Ferrous Sulfate; Oxycodone-Acetaminophen (5mg-325mg); Propofol; Dextrose 50%; Dextrose 5%; Iso-Osmotic Dextrose; Vancomycin; Glucagon.
PROCEDURES HISTORY:
Chronic procedures: Coronary arteriography using two catheters.
New procedures in this visit: Open and other replacement of aortic valve with tissue graft; Left heart cardiac catheterization; (Aorto)coronary bypass of one coronary artery; Extracorporeal circulation auxiliary to open heart surgery; Venous catheterization, not elsewhere classified.

In [24]:
train_df.iloc[12]

subject_id                                                                     10005348
hadm_id                                                                        25239799
admission_category                                                            EMERGENCY
landmark_visit                                                                        3
age_at_landmark                                                                      78
gender                                                                                M
num_total_visits                                                                      3
death_in_90days                                                                       0
med_text                              Ketorolac\nOxycoDONE (Immediate Release) \nHYD...
diag_text                             Malignant neoplasm of lower lobe, bronchus or ...
proc_text                             15 mg of Ketorolac in VIAL through IV\n5-10 mg...
dose_text                             15 mg of Ketorolac in VIAL through IV\n5-10 mg...
new_medications                       0.9% Sodium Chloride\n5% Dextrose\nAcetaminoph...
new_diagnoses                         Aortic valve disorders\nAtherosclerosis of aor...
new_procedures                        (Aorto)coronary bypass of one coronary artery\...
new_dose                              0 UNIT of Insulin in mL through SC\n0.15 % of ...
no_more_diagnoses                     Long-term (current) use of aspirin\nOther and ...
no_more_medications                   Atropine Sulfate\nClopidogrel\nD5 1/2NS\nNitro...
no_more_procedures                    Insertion of drug-eluting coronary artery sten...
no_more_dose                          0.3 mg of Nitroglycerin SL in TAB through SL\n...
meds_per_visit                        {1: ['Ketorolac', 'OxycoDONE (Immediate Releas...
diag_per_visit                        {1: ['Malignant neoplasm of lower lobe, bronch...
proc_per_visit                        {1: ['Thoracoscopic lobectomy of lung', 'Regio...
dose_per_visit                        {1: ['15 mg of Ketorolac in VIAL through IV', ...
gender_numeric                                                                        1
days_since_previous_visit                                                         521.0
admittime                                                           2130-10-26 17:03:00
dischtime                                                           2130-11-02 16:00:00
days_until_next_visit                                                              -1.0
mins_until_next_visit                                                              -1.0
days_since_last_visit                                                             521.0
mins_since_last_visit                                                          750573.0
days_since_last_visit_cumulate                                     [-1.0, 251.0, 521.0]
days_since_last_visit_cumulate_sum                                       [772.0, 521.0]
Name: 330, dtype: object

In [25]:
#ast.literal_eval(train_df['diag_text'])
row = train_df.iloc[12]
list(ast.literal_eval(row['diag_per_visit']).items())

[(1,
  ['Malignant neoplasm of lower lobe, bronchus or lung',
   'Mobitz (type) II atrioventricular block',
   'Loss of weight',
   'Body Mass Index between 19-24, adult',
   'Coronary atherosclerosis of native coronary artery',
   'Percutaneous transluminal coronary angioplasty status',
   'Personal history of malignant neoplasm of prostate',
   'Aortic valve disorders',
   'Cerebral atherosclerosis',
   'Anemia, unspecified',
   'Unspecified essential hypertension',
   'Other and unspecified hyperlipidemia',
   'Impaired glucose tolerance test (oral)',
   'Other and unspecified alcohol dependence, in remission',
   'Osteoarthrosis, unspecified whether generalized or localized, hand',
   'Cervical spondylosis without myelopathy',
   'Lumbosacral spondylosis without myelopathy',
   'Depressive disorder, not elsewhere classified',
   'Unspecified glaucoma',
   'Unspecified hereditary and idiopathic peripheral neuropathy',
   'Dysphonia',
   'Personal history of tobacco use',
   'Retention of urine, unspecified',
   'Orthostatic hypotension',
   'Atrial fibrillation',
   'Hypopotassemia',
   'Disorders of phosphorus metabolism',
   'Disorders of magnesium metabolism']),
 (2,
  ['Coronary atherosclerosis of native coronary artery',
   'Unspecified essential hypertension',
   'Other and unspecified angina pectoris',
   'Other and unspecified hyperlipidemia',
   'Long-term (current) use of aspirin']),
 (3,
  ['Aortic valve disorders',
   'Mobitz (type) II atrioventricular block',
   'Unspecified pleural effusion',
   'Other B-complex deficiencies',
   'Atrial fibrillation',
   'Thrombocytopenia, unspecified',
   'Pulmonary collapse',
   'Cardiac complications, not elsewhere classified',
   'Coronary atherosclerosis of native coronary artery',
   'Unspecified essential hypertension',
   'Osteoarthrosis, unspecified whether generalized or localized, hand',
   'Depressive disorder, not elsewhere classified',
   'Other and unspecified hyperlipidemia',
   'Iron deficiency anemia, unspecified',
   'Orthostatic hypotension',
   'Unspecified glaucoma',
   'Atherosclerosis of aorta',
   'Degeneration of cervical intervertebral disc',
   'Degeneration of lumbar or lumbosacral intervertebral disc',
   'Surgical operation with implant of artificial internal device causing abnormal patient reaction, or later complication,without mention of misadventure at time of operation',
   'Examination of participant in clinical trial',
   'Personal history of malignant neoplasm of prostate',
   'Personal history of malignant neoplasm of bronchus and lung',
   'Personal history of other malignant neoplasm of skin',
   'Family history of ischemic heart disease',
   'Personal history of tobacco use',
   'Percutaneous transluminal coronary angioplasty status',
   'Personal history of alcoholism'])]

In [1]:
# Let's see lenghts:
len_full = len(train_texts_full[12])
len_full_no_time_rnd = len(train_texts_full_no_time_rnd[12])
len_no_narrative = len(train_texts_no_narrative[12])
len_compact = len(train_texts_compact[12])
print(len_full, len_full_no_time_rnd, len_no_narrative, len_compact)

NameError: name 'train_texts_full' is not defined